// <auto-generated/>
#nullable enable
namespace SkiaMarkdown.Syntax.Utf16
{
    /// <summary>
    /// Classifies characters relevant to Markdown tokenization.
    /// </summary>
    internal static class Utf16CharacterClassifier
    {
        public static bool IsWhitespace(char ch) =>
            ch is ' ' or '\t' or '\f' or '\v';

        public static bool IsLineBreak(char ch) => ch is '\r' or '\n';

        public static bool IsPunctuation(char ch) =>
            ch is '*' or '_' or '`' or '~' or '^' or '+'
                or '-' or '.' or ':' or ';' or ',' or '!'
                or '?' or '#' or '|' or '/' or '\\' or '['
                or ']' or '{' or '}' or '(' or ')' or '<'
                or '>' or '\'' or '"' or '=' or '&' or '%'
                or '$' or '@';

        public static bool IsDigit(char ch) => ch is >= '0' and <= '9';

        public static bool IsHex(char ch) =>
            IsDigit(ch) || ch is >= 'a' and <= 'f' || ch is >= 'A' and <= 'F';

        public static bool IsAlpha(char ch) =>
            ch is >= 'a' and <= 'z' || ch is >= 'A' and <= 'Z';

        public static bool IsAlphanumeric(char ch) => IsAlpha(ch) || IsDigit(ch);

        public static bool IsWordCharacter(char ch) =>
            IsAlphanumeric(ch) || ch is '_' or '-' or ':';
    }
}
