// <auto-generated/>
#nullable enable
namespace SkiaMarkdown.Syntax.Red
{
    using System.Collections.Generic;
    using SkiaMarkdown.Syntax;
    using SkiaMarkdown.Syntax.Green;

    /// <summary>
    /// Base type for Roslyn-style red nodes.
    /// </summary>
    public abstract class MarkdownSyntaxNode
    {
        private readonly int position;

        internal MarkdownSyntaxNode(MarkdownSyntaxNode? parent, GreenNode green, int position)
        {
            Parent = parent;
            GreenNode = green;
            this.position = position;
        }

        public MarkdownSyntaxNode? Parent { get; }

        internal GreenNode GreenNode { get; }

        public MarkdownSyntaxKind Kind => GreenNode.Kind;

        public virtual bool IsToken => false;

        public int FullWidth => GreenNode.FullWidth;

        public TextSpan Span => new(position, FullWidth);

        public virtual IEnumerable<MarkdownSyntaxElement> ChildNodesAndTokens()
        {
            yield break;
        }

        public IEnumerable<MarkdownSyntaxNode> ChildNodes()
        {
            foreach (var element in ChildNodesAndTokens())
            {
                if (element.IsNode)
                {
                    yield return element.AsNode();
                }
            }
        }

        public IEnumerable<MarkdownSyntaxToken> ChildTokens()
        {
            foreach (var element in ChildNodesAndTokens())
            {
                if (element.IsToken)
                {
                    yield return element.AsToken();
                }
            }
        }

        public virtual void Accept(MarkdownSyntaxVisitor visitor) => visitor.DefaultVisit(this);

        internal static MarkdownSyntaxNode Create(MarkdownSyntaxNode? parent, GreenNode green, int position)
        {
            if (green.IsToken)
            {
                return new MarkdownSyntaxToken(parent, (GreenToken)green, position);
            }

            return new MarkdownSyntaxInternalNode(parent, green, position);
        }

        private sealed class MarkdownSyntaxInternalNode : MarkdownSyntaxNode
        {
            public MarkdownSyntaxInternalNode(MarkdownSyntaxNode? parent, GreenNode green, int position)
                : base(parent, green, position)
            {
            }

            public override IEnumerable<MarkdownSyntaxElement> ChildNodesAndTokens()
            {
                var current = Span.Start;

                for (var i = 0; i < GreenNode.SlotCount; i++)
                {
                    var childGreen = GreenNode.GetSlot(i);
                    if (childGreen is null)
                    {
                        continue;
                    }

                    var child = CreateInternal(this, childGreen, current);
                    yield return child.IsToken
                        ? new MarkdownSyntaxElement((MarkdownSyntaxToken)child)
                        : new MarkdownSyntaxElement(child);

                    current += childGreen.FullWidth;
                }
            }

            private static MarkdownSyntaxNode CreateInternal(MarkdownSyntaxNode parent, GreenNode childGreen, int position) =>
                childGreen.IsToken
                    ? new MarkdownSyntaxToken(parent, (GreenToken)childGreen, position)
                    : new MarkdownSyntaxInternalNode(parent, childGreen, position);
        }
    }
}
