// <auto-generated/>
#nullable enable
namespace SkiaMarkdown.Syntax.Red
{
    using System;
    using System.Collections.Generic;
    using SkiaMarkdown.Syntax.Green;

    /// <summary>
    /// Represents a Roslyn-style syntax token.
    /// </summary>
    public sealed class MarkdownSyntaxToken : MarkdownSyntaxNode
    {
        private readonly GreenToken greenToken;
        private readonly IReadOnlyList<MarkdownSyntaxTrivia> leadingTrivia;
        private readonly IReadOnlyList<MarkdownSyntaxTrivia> trailingTrivia;

        internal MarkdownSyntaxToken(MarkdownSyntaxNode? parent, GreenToken green, int position)
            : base(parent, green, position)
        {
            greenToken = green;
            leadingTrivia = ConvertTrivia(green.LeadingTrivia);
            trailingTrivia = ConvertTrivia(green.TrailingTrivia);
        }

        public override bool IsToken => true;

        public string Text => greenToken.Text;

        public IReadOnlyList<MarkdownSyntaxTrivia> LeadingTrivia => leadingTrivia;

        public IReadOnlyList<MarkdownSyntaxTrivia> TrailingTrivia => trailingTrivia;

        public override IEnumerable<MarkdownSyntaxElement> ChildNodesAndTokens()
        {
            yield break;
        }

        public override void Accept(MarkdownSyntaxVisitor visitor) => visitor.VisitToken(this);

        private static IReadOnlyList<MarkdownSyntaxTrivia> ConvertTrivia(System.Collections.Immutable.ImmutableArray<GreenTrivia> trivia)
        {
            if (trivia.IsDefaultOrEmpty)
            {
                return Array.Empty<MarkdownSyntaxTrivia>();
            }

            var result = new MarkdownSyntaxTrivia[trivia.Length];
            for (var i = 0; i < trivia.Length; i++)
            {
                result[i] = new MarkdownSyntaxTrivia(trivia[i].Kind, trivia[i].Text);
            }

            return result;
        }
    }
}
