// <auto-generated/>
#nullable enable
namespace SkiaMarkdown.Syntax.Red
{
    using System;

    /// <summary>
    /// Represents either a syntax node or token.
    /// </summary>
    public readonly struct MarkdownSyntaxElement
    {
        private readonly MarkdownSyntaxNode? node;
        private readonly MarkdownSyntaxToken? token;

        public MarkdownSyntaxElement(MarkdownSyntaxNode node)
        {
            this.node = node;
            token = null;
        }

        public MarkdownSyntaxElement(MarkdownSyntaxToken token)
        {
            node = null;
            this.token = token;
        }

        public bool IsNode => node is not null;

        public bool IsToken => token is not null;

        public MarkdownSyntaxNode AsNode() => node ?? throw new InvalidOperationException("Element is not a node.");

        public MarkdownSyntaxToken AsToken() => token ?? throw new InvalidOperationException("Element is not a token.");
    }
}
