// <auto-generated/>
#nullable enable
namespace SkiaMarkdown.Syntax.Red
{
    /// <summary>
    /// Represents trivia attached to syntax tokens.
    /// </summary>
    public readonly record struct MarkdownSyntaxTrivia(MarkdownSyntaxKind Kind, string Text);
}
