// <auto-generated/>
#nullable enable
namespace SkiaMarkdown.Syntax.Red
{
    /// <summary>
    /// Base visitor for Roslyn-style Markdown syntax trees.
    /// </summary>
    public class MarkdownSyntaxVisitor
    {
        public virtual void Visit(MarkdownSyntaxNode node)
        {
            if (node.IsToken && node is MarkdownSyntaxToken token)
            {
                VisitToken(token);
                return;
            }

            DefaultVisit(node);
        }

        public virtual void VisitToken(MarkdownSyntaxToken token)
        {
        }

        public virtual void DefaultVisit(MarkdownSyntaxNode node)
        {
            foreach (var element in node.ChildNodesAndTokens())
            {
                if (element.IsNode)
                {
                    Visit(element.AsNode());
                }
                else
                {
                    VisitToken(element.AsToken());
                }
            }
        }
    }
}
