// <auto-generated/>
#nullable enable
namespace SkiaMarkdown.Syntax.Parsing
{
    /// <summary>
    /// Identifies the type of token encountered in the Markdown source.
    /// </summary>
    internal enum MarkdownTokenKind : ushort
    {
        None = 0,
        EndOfFile,
        BlankLine,
        Heading,
        Paragraph,
        BlockQuote,
        FencedCodeBlock,
        IndentedCodeBlock,
        OrderedListItem,
        UnorderedListItem,
        ThematicBreak,
    HtmlBlock,
    CustomContainer,
    FootnoteDefinition,
        Table,
        Text,
    }
}
