// <auto-generated/>
#nullable enable
namespace SkiaMarkdown.Syntax.Parsing
{
    using SkiaMarkdown.Syntax;

    /// <summary>
    /// Describes a lexical token identified by the tokenizer.
    /// </summary>
    internal readonly record struct MarkdownToken(
        MarkdownTokenKind Kind,
        TextSpan Span,
        int Line,
        int Column,
        int Value)
    {
        public static MarkdownToken End(TextSpan span, int line, int column) =>
            new(MarkdownTokenKind.EndOfFile, span, line, column, 0);
    }
}
