// <auto-generated/>
#nullable enable
namespace SkiaMarkdown.Syntax.Generation
{
    using System.Collections.Immutable;

    /// <summary>
    /// Provides canonical descriptors for GitHub Flavored Markdown nodes.
    /// </summary>
    internal static class MarkdownSyntaxRegistry
    {
        private static readonly ImmutableArray<MarkdownSyntaxDescriptor> Descriptors =
            ImmutableArray.Create(
                MarkdownSyntaxDescriptor.Create(
                    "MarkdownDocument",
                    MarkdownSyntaxKind.MarkdownDocument,
                    MarkdownSyntaxKind.SyntaxList),
                MarkdownSyntaxDescriptor.Create(
                    "ParagraphBlock",
                    MarkdownSyntaxKind.ParagraphBlock,
                    MarkdownSyntaxKind.SyntaxList),
                MarkdownSyntaxDescriptor.Create(
                    "AtxHeadingBlock",
                    MarkdownSyntaxKind.AtxHeadingBlock,
                    MarkdownSyntaxKind.HeadingPunctuation,
                    MarkdownSyntaxKind.HeadingText),
                MarkdownSyntaxDescriptor.Create(
                    "SetextHeadingBlock",
                    MarkdownSyntaxKind.SetextHeadingBlock,
                    MarkdownSyntaxKind.HeadingText,
                    MarkdownSyntaxKind.HeadingPunctuation),
                MarkdownSyntaxDescriptor.Create(
                    "BlockQuoteBlock",
                    MarkdownSyntaxKind.BlockQuoteBlock,
                    MarkdownSyntaxKind.BlockQuotePrefix,
                    MarkdownSyntaxKind.SyntaxList),
                MarkdownSyntaxDescriptor.Create(
                    "BulletListBlock",
                    MarkdownSyntaxKind.BulletListBlock,
                    MarkdownSyntaxKind.SyntaxList),
                MarkdownSyntaxDescriptor.Create(
                    "OrderedListBlock",
                    MarkdownSyntaxKind.OrderedListBlock,
                    MarkdownSyntaxKind.SyntaxList),
                MarkdownSyntaxDescriptor.Create(
                    "ListItemBlock",
                    MarkdownSyntaxKind.ListItemBlock,
                    MarkdownSyntaxKind.SyntaxList),
                MarkdownSyntaxDescriptor.Create(
                    "TaskListItemBlock",
                    MarkdownSyntaxKind.TaskListItemBlock,
                    MarkdownSyntaxKind.TaskListState,
                    MarkdownSyntaxKind.SyntaxList),
                MarkdownSyntaxDescriptor.Create(
                    "IndentedCodeBlock",
                    MarkdownSyntaxKind.IndentedCodeBlock,
                    MarkdownSyntaxKind.FencedCodeText),
                MarkdownSyntaxDescriptor.Create(
                    "FencedCodeBlock",
                    MarkdownSyntaxKind.FencedCodeBlock,
                    MarkdownSyntaxKind.FencedCodeFence,
                    MarkdownSyntaxKind.FencedCodeText,
                    MarkdownSyntaxKind.FencedCodeFence),
                MarkdownSyntaxDescriptor.Create(
                    "HtmlBlock",
                    MarkdownSyntaxKind.HtmlBlock,
                    MarkdownSyntaxKind.SyntaxList),
                MarkdownSyntaxDescriptor.Create(
                    "TableBlock",
                    MarkdownSyntaxKind.TableBlock,
                    MarkdownSyntaxKind.TableHeader,
                    MarkdownSyntaxKind.TableDelimiterRow,
                    MarkdownSyntaxKind.TableBody));

        public static ImmutableArray<MarkdownSyntaxDescriptor> GetDescriptors() => Descriptors;
    }
}
