// <auto-generated/>
#nullable enable
namespace SkiaMarkdown.Syntax.Generation
{
    using System.Collections.Immutable;

    /// <summary>
    /// Describes a Markdown syntax node for downstream code generation.
    /// </summary>
    internal sealed record MarkdownSyntaxDescriptor(
        string Name,
        MarkdownSyntaxKind Kind,
        ImmutableArray<MarkdownSyntaxKind> ChildKinds,
        bool IsList = false)
    {
        public static MarkdownSyntaxDescriptor Create(
            string name,
            MarkdownSyntaxKind kind,
            params MarkdownSyntaxKind[] childKinds) =>
            new(name, kind, ImmutableArray.Create(childKinds));
    }
}
