// <auto-generated/>
#nullable enable
namespace SkiaMarkdown.Syntax.Tokenizer
{
    using System;
    using System.Collections.Generic;
    using System.Collections.Immutable;
    using SkiaMarkdown.Syntax.Green;

    /// <summary>
    /// Utility for constructing Markdown tokens with precise leading and trailing trivia.
    /// </summary>
    internal sealed class MarkdownTokenBuilder
    {
        private readonly List<GreenTrivia> leadingTrivia = new();
        private readonly List<GreenTrivia> trailingTrivia = new();

        public void AddLeadingTrivia(GreenTrivia trivia)
        {
            if (trivia is null)
            {
                throw new ArgumentNullException(nameof(trivia));
            }

            leadingTrivia.Add(trivia);
        }

        public void AddTrailingTrivia(GreenTrivia trivia)
        {
            if (trivia is null)
            {
                throw new ArgumentNullException(nameof(trivia));
            }

            trailingTrivia.Add(trivia);
        }

        public GreenToken CreateToken(MarkdownSyntaxKind kind, string text)
        {
            if (text is null)
            {
                throw new ArgumentNullException(nameof(text));
            }

            return MarkdownSyntaxFactory.Token(
                kind,
                text,
                leadingTrivia.ToImmutableArray(),
                trailingTrivia.ToImmutableArray());
        }

        public void Reset()
        {
            leadingTrivia.Clear();
            trailingTrivia.Clear();
        }
    }
}
