// <auto-generated/>
#nullable enable
namespace SkiaMarkdown.Syntax.Semantics
{
    using System.Collections.Generic;

    /// <summary>
    /// Base type for resolved inline semantics.
    /// </summary>
    public abstract record MarkdownInlineSemantic;

    public sealed record TextInlineSemantic(string Text) : MarkdownInlineSemantic;

    public sealed record CodeSpanInlineSemantic(string Text) : MarkdownInlineSemantic;

    public sealed record EmphasisInlineSemantic(IReadOnlyList<MarkdownInlineSemantic> Children) : MarkdownInlineSemantic;

    public sealed record StrongInlineSemantic(IReadOnlyList<MarkdownInlineSemantic> Children) : MarkdownInlineSemantic;

    public sealed record StrikethroughInlineSemantic(IReadOnlyList<MarkdownInlineSemantic> Children) : MarkdownInlineSemantic;

    public sealed record HighlightInlineSemantic(IReadOnlyList<MarkdownInlineSemantic> Children) : MarkdownInlineSemantic;

    public sealed record MathInlineSemantic(string Expression) : MarkdownInlineSemantic;

    public sealed record LinkInlineSemantic(IReadOnlyList<MarkdownInlineSemantic> Children, string Destination) : MarkdownInlineSemantic;

    public sealed record ImageInlineSemantic(IReadOnlyList<MarkdownInlineSemantic> AlternativeText, string Source) : MarkdownInlineSemantic;

    public sealed record AutolinkInlineSemantic(string Url) : MarkdownInlineSemantic;

    public sealed record HtmlInlineSemantic(string Html) : MarkdownInlineSemantic;

    public sealed record EntityInlineSemantic(string Value) : MarkdownInlineSemantic;

    public sealed record BreakInlineSemantic(bool IsHard) : MarkdownInlineSemantic;

    public sealed record TaskListMarkerInlineSemantic(bool IsChecked) : MarkdownInlineSemantic;

    public sealed record EmojiInlineSemantic(string Shortcode) : MarkdownInlineSemantic;

    public sealed record MentionInlineSemantic(string Identifier) : MarkdownInlineSemantic;

    public sealed record FootnoteReferenceInlineSemantic(string Label) : MarkdownInlineSemantic;
}
