// <auto-generated/>
#nullable enable
namespace SkiaMarkdown.Syntax.Semantics
{
    /// <summary>
    /// Represents a diagnostic produced during semantic analysis.
    /// </summary>
    public sealed record MarkdownDiagnostic(string Id, string Message, TextSpan Span, MarkdownDiagnosticSeverity Severity = MarkdownDiagnosticSeverity.Warning);

    public enum MarkdownDiagnosticSeverity
    {
        Info,
        Warning,
        Error
    }
}
