// <auto-generated/>
#nullable enable
namespace SkiaMarkdown.Syntax.Semantics
{
    using System.Collections.Generic;

    public enum MarkdownTableColumnAlignment
    {
        None,
        Left,
        Center,
        Right
    }

    public sealed record MarkdownTableCellSemantic(
        IReadOnlyList<MarkdownInlineSemantic> Inlines,
        IReadOnlyList<MarkdownDiagnostic> Diagnostics);

    public sealed record MarkdownTableRowSemantic(IReadOnlyList<MarkdownTableCellSemantic> Cells);

    public sealed record MarkdownTableSemantic(
        IReadOnlyList<MarkdownTableColumnAlignment> Alignments,
        MarkdownTableRowSemantic Header,
        IReadOnlyList<MarkdownTableRowSemantic> Body,
        IReadOnlyList<MarkdownDiagnostic> Diagnostics);
}
