// <auto-generated/>
#nullable enable
namespace SkiaMarkdown.Syntax.Green
{
    using System.Collections.Immutable;

    /// <summary>
    /// Represents an immutable Markdown token in the Roslyn-style green tree.
    /// </summary>
    internal sealed class GreenToken : GreenNode
    {
        private readonly string text;
        private readonly ImmutableArray<GreenTrivia> leadingTrivia;
        private readonly ImmutableArray<GreenTrivia> trailingTrivia;

        public GreenToken(
            MarkdownSyntaxKind kind,
            string text,
            ImmutableArray<GreenTrivia> leadingTrivia,
            ImmutableArray<GreenTrivia> trailingTrivia)
            : base(kind, CalculateFullWidth(text, leadingTrivia, trailingTrivia))
        {
            this.text = text;
            this.leadingTrivia = leadingTrivia.IsDefault ? ImmutableArray<GreenTrivia>.Empty : leadingTrivia;
            this.trailingTrivia = trailingTrivia.IsDefault ? ImmutableArray<GreenTrivia>.Empty : trailingTrivia;
        }

        public override bool IsToken => true;

        public string Text => text;

        public ImmutableArray<GreenTrivia> LeadingTrivia => leadingTrivia;

        public ImmutableArray<GreenTrivia> TrailingTrivia => trailingTrivia;

        public override string? GetText() => text;

        private static int CalculateFullWidth(
            string text,
            ImmutableArray<GreenTrivia> leadingTrivia,
            ImmutableArray<GreenTrivia> trailingTrivia)
        {
            var width = text.Length;

            if (!leadingTrivia.IsDefaultOrEmpty)
            {
                foreach (var trivia in leadingTrivia)
                {
                    width += trivia.FullWidth;
                }
            }

            if (!trailingTrivia.IsDefaultOrEmpty)
            {
                foreach (var trivia in trailingTrivia)
                {
                    width += trivia.FullWidth;
                }
            }

            return width;
        }
    }
}
