// <auto-generated/>
#nullable enable
namespace SkiaMarkdown.Syntax.Green
{
    using System.Collections.Generic;

    /// <summary>
    /// Represents a homogeneous list of child nodes within the green tree.
    /// </summary>
    internal sealed class GreenListNode : GreenNode
    {
        private readonly GreenNode?[] children;

        public GreenListNode(IReadOnlyList<GreenNode?> children)
            : base(MarkdownSyntaxKind.SyntaxList, CalculateFullWidth(children))
        {
            this.children = new GreenNode?[children.Count];
            for (var i = 0; i < children.Count; i++)
            {
                this.children[i] = children[i];
            }
        }

        public override int SlotCount => children.Length;

        public override GreenNode? GetSlot(int index) =>
            (uint)index < (uint)children.Length ? children[index] : null;

        private static int CalculateFullWidth(IReadOnlyList<GreenNode?> nodes)
        {
            var width = 0;
            for (var i = 0; i < nodes.Count; i++)
            {
                var child = nodes[i];
                if (child is not null)
                {
                    width += child.FullWidth;
                }
            }

            return width;
        }
    }
}
