// <auto-generated/>
#nullable enable
namespace SkiaMarkdown.Syntax.Green
{
    using System;

    /// <summary>
    /// Helper base class for green nodes that contain child slots.
    /// </summary>
    internal abstract class GreenNodeWithSlots : GreenNode
    {
        private readonly GreenNode?[] children;

        private protected GreenNodeWithSlots(MarkdownSyntaxKind kind, GreenNode?[] children)
            : base(kind, CalculateFullWidth(children))
        {
            this.children = children;
        }

        public override int SlotCount => children.Length;

        public override GreenNode? GetSlot(int index) =>
            (uint)index < (uint)children.Length ? children[index] : null;

        private static int CalculateFullWidth(ReadOnlySpan<GreenNode?> childNodes)
        {
            var width = 0;
            foreach (var child in childNodes)
            {
                if (child is not null)
                {
                    width += child.FullWidth;
                }
            }

            return width;
        }
    }
}
