// <auto-generated/>
#nullable enable
namespace SkiaMarkdown.Syntax.Green
{
    using System.Collections.Generic;

    /// <summary>
    /// Base type for immutable Markdown syntax nodes in the Roslyn-style green tree.
    /// </summary>
    internal abstract class GreenNode
    {
        private protected GreenNode(MarkdownSyntaxKind kind, int fullWidth)
        {
            Kind = kind;
            FullWidth = fullWidth;
        }

        public MarkdownSyntaxKind Kind { get; }

        public int FullWidth { get; }

        public virtual bool IsToken => false;

        public virtual bool IsTrivia => false;

        public virtual int SlotCount => 0;

        public virtual GreenNode? GetSlot(int index) => null;

        public virtual string? GetText() => null;

        public virtual IEnumerable<GreenNode> ChildNodesAndTokens()
        {
            for (var i = 0; i < SlotCount; i++)
            {
                var child = GetSlot(i);
                if (child is not null)
                {
                    yield return child;
                }
            }
        }
    }
}
