// <auto-generated/>
#nullable enable
namespace SkiaMarkdown.Syntax.Green
{
    /// <summary>
    /// Represents immutable trivia in the Roslyn-style green tree.
    /// </summary>
    internal sealed class GreenTrivia : GreenNode
    {
        private readonly string text;

        public GreenTrivia(MarkdownSyntaxKind kind, string text)
            : base(kind, text.Length)
        {
            this.text = text;
        }

        public override bool IsTrivia => true;

        public string Text => text;

        public override string? GetText() => text;
    }
}
