// <auto-generated/>
#nullable enable
namespace SkiaMarkdown.Syntax.Green
{
    /// <summary>
    /// Represents a Roslyn-style green node with a fixed set of child slots.
    /// </summary>
    internal sealed class GreenInternalNode : GreenNodeWithSlots
    {
        public GreenInternalNode(MarkdownSyntaxKind kind, GreenNode?[] children)
            : base(kind, children)
        {
        }
    }
}
