// <auto-generated/>
#nullable enable
namespace SkiaMarkdown.Syntax
{
    using System;
    using System.Collections.Generic;
    using System.Collections.Immutable;
    using SkiaMarkdown.Syntax.Green;

    /// <summary>
    /// Provides helpers to construct Roslyn-style green nodes for Markdown syntax.
    /// </summary>
    internal static class MarkdownSyntaxFactory
    {
        public static GreenToken Token(
            MarkdownSyntaxKind kind,
            string text,
            ImmutableArray<GreenTrivia> leadingTrivia = default,
            ImmutableArray<GreenTrivia> trailingTrivia = default)
        {
            if (text is null)
            {
                throw new ArgumentNullException(nameof(text));
            }

            return new GreenToken(kind, text, leadingTrivia, trailingTrivia);
        }

        public static GreenTrivia Trivia(MarkdownSyntaxKind kind, string text)
        {
            if (text is null)
            {
                throw new ArgumentNullException(nameof(text));
            }

            return new GreenTrivia(kind, text);
        }

        public static GreenNode Node(MarkdownSyntaxKind kind, params GreenNode?[] children)
        {
            if (children is null)
            {
                throw new ArgumentNullException(nameof(children));
            }

            var copy = new GreenNode?[children.Length];
            Array.Copy(children, copy, children.Length);
            return new GreenInternalNode(kind, copy);
        }

        public static GreenNode CreateList(IEnumerable<GreenNode?> nodes)
        {
            if (nodes is null)
            {
                throw new ArgumentNullException(nameof(nodes));
            }

            if (nodes is IReadOnlyList<GreenNode?> list)
            {
                return new GreenListNode(list);
            }

            var builder = new List<GreenNode?>();
            builder.AddRange(nodes);
            return new GreenListNode(builder);
        }
    }
}
