// <auto-generated/>
#nullable enable
namespace SkiaMarkdown.Syntax
{
    /// <summary>
    /// Configures Roslyn-style Markdown parsing features.
    /// </summary>
    public sealed class MarkdownSyntaxOptions
    {
        public static MarkdownSyntaxOptions Default { get; } = new();

        public bool EnableGitHubExtensions { get; init; } = true;

        public bool EnableEmojiShortcodes { get; init; } = true;

        public bool EnableMentions { get; init; } = true;

        public bool EnableInlineMath { get; init; } = true;

        public bool EnableFootnotes { get; init; } = true;

        public bool EnableStrikethrough { get; init; } = true;

        public bool EnableHighlight { get; init; } = true;

        public bool EnableTableAlignment { get; init; } = true;

        public bool EnableTaskLists { get; init; } = true;
    }
}
