// <auto-generated/>
#nullable enable
namespace SkiaMarkdown.Syntax
{
    using System;
    using System.Collections.Concurrent;
    using SkiaMarkdown.Syntax.Green;

    /// <summary>
    /// Caches reusable trivia instances to minimise allocations while constructing green trees.
    /// </summary>
    internal static class MarkdownTriviaTable
    {
        private static readonly ConcurrentDictionary<string, GreenTrivia> WhitespaceTrivia = new(StringComparer.Ordinal);

        private static readonly GreenTrivia LineFeedTrivia =
            MarkdownSyntaxFactory.Trivia(MarkdownSyntaxKind.EndOfLineTrivia, "\n");

        private static readonly GreenTrivia CarriageReturnLineFeedTrivia =
            MarkdownSyntaxFactory.Trivia(MarkdownSyntaxKind.CarriageReturnLineFeedTrivia, "\r\n");

        public static GreenTrivia GetWhitespaceTrivia(int length)
        {
            if (length <= 0)
            {
                throw new ArgumentOutOfRangeException(nameof(length), length, "Length must be positive.");
            }

            var text = new string(' ', length);
            return WhitespaceTrivia.GetOrAdd(text, static key =>
                MarkdownSyntaxFactory.Trivia(MarkdownSyntaxKind.WhitespaceTrivia, key));
        }

        public static GreenTrivia GetTabTrivia() =>
            WhitespaceTrivia.GetOrAdd("\t", static key =>
                MarkdownSyntaxFactory.Trivia(MarkdownSyntaxKind.TabTrivia, key));

        public static GreenTrivia GetLineFeedTrivia() => LineFeedTrivia;

        public static GreenTrivia GetCarriageReturnLineFeedTrivia() => CarriageReturnLineFeedTrivia;
    }
}
