// <auto-generated/>
#nullable enable
namespace SkiaMarkdown.Syntax
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Provides classification helpers and textual representations for Markdown syntax kinds.
    /// </summary>
    public static class MarkdownSyntaxFacts
    {
        private static readonly Dictionary<MarkdownSyntaxKind, string> TokenTexts = new()
        {
            { MarkdownSyntaxKind.AsteriskToken, "*" },
            { MarkdownSyntaxKind.UnderscoreToken, "_" },
            { MarkdownSyntaxKind.BacktickToken, "`" },
            { MarkdownSyntaxKind.TildeToken, "~" },
            { MarkdownSyntaxKind.CaretToken, "^" },
            { MarkdownSyntaxKind.PlusToken, "+" },
            { MarkdownSyntaxKind.MinusToken, "-" },
            { MarkdownSyntaxKind.DotToken, "." },
            { MarkdownSyntaxKind.ColonToken, ":" },
            { MarkdownSyntaxKind.SemicolonToken, ";" },
            { MarkdownSyntaxKind.CommaToken, "," },
            { MarkdownSyntaxKind.ExclamationToken, "!" },
            { MarkdownSyntaxKind.QuestionToken, "?" },
            { MarkdownSyntaxKind.HashToken, "#" },
            { MarkdownSyntaxKind.PipeToken, "|" },
            { MarkdownSyntaxKind.SlashToken, "/" },
            { MarkdownSyntaxKind.BackslashToken, "\\" },
            { MarkdownSyntaxKind.OpenBracketToken, "[" },
            { MarkdownSyntaxKind.CloseBracketToken, "]" },
            { MarkdownSyntaxKind.OpenBraceToken, "{" },
            { MarkdownSyntaxKind.CloseBraceToken, "}" },
            { MarkdownSyntaxKind.OpenParenToken, "(" },
            { MarkdownSyntaxKind.CloseParenToken, ")" },
            { MarkdownSyntaxKind.LessThanToken, "<" },
            { MarkdownSyntaxKind.GreaterThanToken, ">" },
            { MarkdownSyntaxKind.SingleQuoteToken, "'" },
            { MarkdownSyntaxKind.DoubleQuoteToken, "\"" },
            { MarkdownSyntaxKind.EqualToken, "=" },
            { MarkdownSyntaxKind.AmpersandToken, "&" },
            { MarkdownSyntaxKind.PercentToken, "%" },
            { MarkdownSyntaxKind.DollarToken, "$" },
            { MarkdownSyntaxKind.AtSignToken, "@" },
            { MarkdownSyntaxKind.CodeFenceMarkerToken, "```" },
        };

        private static readonly Dictionary<MarkdownSyntaxKind, string> TriviaTexts = new()
        {
            { MarkdownSyntaxKind.WhitespaceTrivia, " " },
            { MarkdownSyntaxKind.TabTrivia, "\t" },
            { MarkdownSyntaxKind.EndOfLineTrivia, "\n" },
            { MarkdownSyntaxKind.CarriageReturnLineFeedTrivia, "\r\n" },
        };

        public static bool IsTrivia(MarkdownSyntaxKind kind) =>
            kind is MarkdownSyntaxKind.WhitespaceTrivia
                or MarkdownSyntaxKind.TabTrivia
                or MarkdownSyntaxKind.EndOfLineTrivia
                or MarkdownSyntaxKind.CarriageReturnLineFeedTrivia
                or MarkdownSyntaxKind.HtmlCommentTrivia;

        public static bool IsToken(MarkdownSyntaxKind kind) =>
            kind switch
            {
                MarkdownSyntaxKind.BadToken => true,
                MarkdownSyntaxKind.EndOfFileToken => true,
                MarkdownSyntaxKind.TableAlignmentToken => true,
                >= MarkdownSyntaxKind.TextToken and <= MarkdownSyntaxKind.HtmlCDataEndToken => true,
                _ => false,
            };

        public static bool IsNode(MarkdownSyntaxKind kind) =>
            !IsToken(kind) && kind != MarkdownSyntaxKind.SyntaxList;

        public static bool IsBlockNode(MarkdownSyntaxKind kind) =>
            kind is MarkdownSyntaxKind.MarkdownDocument
                or MarkdownSyntaxKind.ParagraphBlock
                or MarkdownSyntaxKind.AtxHeadingBlock
                or MarkdownSyntaxKind.SetextHeadingBlock
                or MarkdownSyntaxKind.HeadingText
                or MarkdownSyntaxKind.ThematicBreakBlock
                or MarkdownSyntaxKind.BlockQuoteBlock
                or MarkdownSyntaxKind.BulletListBlock
                or MarkdownSyntaxKind.OrderedListBlock
                or MarkdownSyntaxKind.ListItemBlock
                or MarkdownSyntaxKind.TaskListItemBlock
                or MarkdownSyntaxKind.IndentedCodeBlock
                or MarkdownSyntaxKind.FencedCodeBlock
                or MarkdownSyntaxKind.FencedCodeFence
                or MarkdownSyntaxKind.FencedCodeInfo
                or MarkdownSyntaxKind.FencedCodeText
                or MarkdownSyntaxKind.HtmlBlock
                or MarkdownSyntaxKind.LinkDefinitionBlock
                or MarkdownSyntaxKind.FootnoteDefinitionBlock
                or MarkdownSyntaxKind.TableBlock
                or MarkdownSyntaxKind.TableHeader
                or MarkdownSyntaxKind.TableBody
                or MarkdownSyntaxKind.TableRow
                or MarkdownSyntaxKind.TableCell
                or MarkdownSyntaxKind.TableDelimiterRow
                or MarkdownSyntaxKind.TableDelimiterCell
                or MarkdownSyntaxKind.CustomContainerBlock;

        public static bool IsInlineNode(MarkdownSyntaxKind kind) =>
            kind is MarkdownSyntaxKind.TextInline
                or MarkdownSyntaxKind.CodeSpanInline
                or MarkdownSyntaxKind.EmphasisInline
                or MarkdownSyntaxKind.StrongEmphasisInline
            or MarkdownSyntaxKind.StrikethroughInline
            or MarkdownSyntaxKind.HighlightInline
            or MarkdownSyntaxKind.MathInline
            or MarkdownSyntaxKind.LinkInline
                or MarkdownSyntaxKind.ImageInline
                or MarkdownSyntaxKind.AutolinkInline
                or MarkdownSyntaxKind.HtmlInline
                or MarkdownSyntaxKind.EntityInline
                or MarkdownSyntaxKind.LineBreakInline
                or MarkdownSyntaxKind.SoftBreakInline
                or MarkdownSyntaxKind.HardBreakInline
                or MarkdownSyntaxKind.FootnoteReferenceInline
                or MarkdownSyntaxKind.EmojiInline
                or MarkdownSyntaxKind.MentionInline;

        public static bool IsPunctuation(MarkdownSyntaxKind kind) =>
            kind is MarkdownSyntaxKind.AsteriskToken
                or MarkdownSyntaxKind.UnderscoreToken
                or MarkdownSyntaxKind.BacktickToken
                or MarkdownSyntaxKind.TildeToken
                or MarkdownSyntaxKind.CaretToken
                or MarkdownSyntaxKind.PlusToken
                or MarkdownSyntaxKind.MinusToken
                or MarkdownSyntaxKind.DotToken
                or MarkdownSyntaxKind.ColonToken
                or MarkdownSyntaxKind.SemicolonToken
                or MarkdownSyntaxKind.CommaToken
                or MarkdownSyntaxKind.ExclamationToken
                or MarkdownSyntaxKind.QuestionToken
                or MarkdownSyntaxKind.HashToken
                or MarkdownSyntaxKind.PipeToken
                or MarkdownSyntaxKind.SlashToken
                or MarkdownSyntaxKind.BackslashToken
                or MarkdownSyntaxKind.OpenBracketToken
                or MarkdownSyntaxKind.CloseBracketToken
                or MarkdownSyntaxKind.OpenBraceToken
                or MarkdownSyntaxKind.CloseBraceToken
                or MarkdownSyntaxKind.OpenParenToken
                or MarkdownSyntaxKind.CloseParenToken
                or MarkdownSyntaxKind.LessThanToken
                or MarkdownSyntaxKind.GreaterThanToken
                or MarkdownSyntaxKind.SingleQuoteToken
                or MarkdownSyntaxKind.DoubleQuoteToken
                or MarkdownSyntaxKind.EqualToken
                or MarkdownSyntaxKind.AmpersandToken
                or MarkdownSyntaxKind.PercentToken
                or MarkdownSyntaxKind.DollarToken
                or MarkdownSyntaxKind.AtSignToken;

        public static string? GetText(MarkdownSyntaxKind kind)
        {
            if (TokenTexts.TryGetValue(kind, out var tokenText))
            {
                return tokenText;
            }

            if (TriviaTexts.TryGetValue(kind, out var triviaText))
            {
                return triviaText;
            }

            return null;
        }

        public static MarkdownSyntaxKind GetTokenKind(char ch)
        {
            if (char.IsDigit(ch))
            {
                return MarkdownSyntaxKind.DigitsToken;
            }

            if (char.IsLetter(ch))
            {
                return MarkdownSyntaxKind.IdentifierToken;
            }

            return ch switch
            {
                '*' => MarkdownSyntaxKind.AsteriskToken,
                '_' => MarkdownSyntaxKind.UnderscoreToken,
                '`' => MarkdownSyntaxKind.BacktickToken,
                '~' => MarkdownSyntaxKind.TildeToken,
                '^' => MarkdownSyntaxKind.CaretToken,
                '+' => MarkdownSyntaxKind.PlusToken,
                '-' => MarkdownSyntaxKind.MinusToken,
                '.' => MarkdownSyntaxKind.DotToken,
                ':' => MarkdownSyntaxKind.ColonToken,
                ';' => MarkdownSyntaxKind.SemicolonToken,
                ',' => MarkdownSyntaxKind.CommaToken,
                '!' => MarkdownSyntaxKind.ExclamationToken,
                '?' => MarkdownSyntaxKind.QuestionToken,
                '#' => MarkdownSyntaxKind.HashToken,
                '|' => MarkdownSyntaxKind.PipeToken,
                '/' => MarkdownSyntaxKind.SlashToken,
                '\\' => MarkdownSyntaxKind.BackslashToken,
                '[' => MarkdownSyntaxKind.OpenBracketToken,
                ']' => MarkdownSyntaxKind.CloseBracketToken,
                '{' => MarkdownSyntaxKind.OpenBraceToken,
                '}' => MarkdownSyntaxKind.CloseBraceToken,
                '(' => MarkdownSyntaxKind.OpenParenToken,
                ')' => MarkdownSyntaxKind.CloseParenToken,
                '<' => MarkdownSyntaxKind.LessThanToken,
                '>' => MarkdownSyntaxKind.GreaterThanToken,
                '\'' => MarkdownSyntaxKind.SingleQuoteToken,
                '"' => MarkdownSyntaxKind.DoubleQuoteToken,
                '=' => MarkdownSyntaxKind.EqualToken,
                '&' => MarkdownSyntaxKind.AmpersandToken,
                '%' => MarkdownSyntaxKind.PercentToken,
                '$' => MarkdownSyntaxKind.DollarToken,
                '@' => MarkdownSyntaxKind.AtSignToken,
                _ => MarkdownSyntaxKind.TextToken,
            };
        }

        public static bool IsLineBreakTrivia(MarkdownSyntaxKind kind) =>
            kind is MarkdownSyntaxKind.EndOfLineTrivia or MarkdownSyntaxKind.CarriageReturnLineFeedTrivia;

        public static bool IsWhitespaceTrivia(MarkdownSyntaxKind kind) =>
            kind is MarkdownSyntaxKind.WhitespaceTrivia or MarkdownSyntaxKind.TabTrivia;

        public static bool IsFenceMarkerToken(MarkdownSyntaxKind kind) =>
            kind is MarkdownSyntaxKind.CodeFenceMarkerToken
                or MarkdownSyntaxKind.BacktickToken
                or MarkdownSyntaxKind.TildeToken;

        public static ReadOnlySpan<char> GetFenceMarkerCharacter(MarkdownSyntaxKind kind) =>
            kind switch
            {
                MarkdownSyntaxKind.BacktickToken => "`",
                MarkdownSyntaxKind.TildeToken => "~",
                MarkdownSyntaxKind.CodeFenceMarkerToken => "`",
                _ => string.Empty,
            };
    }
}
