// <auto-generated/>
#nullable enable
namespace SkiaMarkdown.Syntax
{
    using System;

    /// <summary>
    /// Represents a segment within a source text.
    /// </summary>
    public readonly record struct TextSpan(int Start, int Length)
    {
        public int End => Start + Length;

        public static TextSpan FromBounds(int start, int end)
        {
            if (end < start)
            {
                throw new ArgumentOutOfRangeException(nameof(end));
            }

            return new TextSpan(start, end - start);
        }

        public bool Contains(int position) => position >= Start && position < End;

        public override string ToString() => $"[{Start}..{End})";
    }
}
