// <auto-generated/>
#nullable enable
namespace SkiaMarkdown.Syntax.Utilities
{
    using System;
    using System.Runtime.CompilerServices;
    using System.Runtime.InteropServices;
    using System.Runtime.Intrinsics;

    /// <summary>
    /// Provides SIMD-accelerated helpers for character searches.
    /// </summary>
    internal static class SimdCharSearch
    {
        public static int IndexOfAny(ReadOnlySpan<char> span, ReadOnlySpan<char> values)
        {
            if (values.IsEmpty)
            {
                return -1;
            }

            if (Vector128.IsHardwareAccelerated && span.Length >= Vector128<ushort>.Count)
            {
                var result = IndexOfAnyVector(span, values);
                if (result >= 0)
                {
                    return result;
                }
            }

            return span.IndexOfAny(values);
        }

        private static int IndexOfAnyVector(ReadOnlySpan<char> span, ReadOnlySpan<char> values)
        {
            var vectorLength = Vector128<ushort>.Count;
            var length = span.Length;
            ref var searchRef = ref MemoryMarshal.GetReference(span);

            Span<Vector128<ushort>> needles = values.Length <= 16
                ? stackalloc Vector128<ushort>[values.Length]
                : new Vector128<ushort>[values.Length];

            for (var i = 0; i < values.Length; i++)
            {
                needles[i] = Vector128.Create((ushort)values[i]);
            }

            Span<ushort> matchBuffer = stackalloc ushort[vectorLength];
            var index = 0;

            while (index <= length - vectorLength)
            {
                var current = LoadVector(ref searchRef, index);
                var compare = Vector128.Equals(current, needles[0]);

                for (var n = 1; n < needles.Length; n++)
                {
                    compare = Vector128.BitwiseOr(compare, Vector128.Equals(current, needles[n]));
                }

                compare.CopyTo(matchBuffer);
                for (var j = 0; j < vectorLength; j++)
                {
                    if (matchBuffer[j] != 0)
                    {
                        return index + j;
                    }
                }

                index += vectorLength;
            }

            return -1;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static Vector128<ushort> LoadVector(ref char source, int index) =>
            Vector128.LoadUnsafe(ref Unsafe.Add(ref source, index)).AsUInt16();
    }
}
